# Generated by Django 3.0.7 on 2020-06-12 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20200608_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(blank=True, default='', max_length=50)),
                ('default_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('default_street_address1', models.CharField(blank=True, default='', max_length=80)),
                ('default_street_address2', models.CharField(blank=True, default='', max_length=80)),
                ('default_city', models.CharField(blank=True, default='', max_length=40)),
                ('default_county', models.CharField(blank=True, default='', max_length=80)),
                ('default_postcode', models.CharField(blank=True, default='', max_length=20)),
                ('default_country', django_countries.fields.CountryField(blank=True, default='', max_length=2)),
                ('liked_products', models.ManyToManyField(related_name='users', to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
