# Generated by Django 3.0.7 on 2020-06-12 23:31

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200608_0232'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_city',
            new_name='default_shipping_city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_country',
            new_name='default_shipping_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_county',
            new_name='default_shipping_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_name',
            new_name='default_shipping_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_postcode',
            new_name='default_shipping_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_street_address1',
            new_name='default_shipping_street_address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_street_address2',
            new_name='default_shipping_street_address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_phone_number',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_city',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_county',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_street_address1',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_billing_street_address2',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_shipping_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='users', to='products.Product'),
        ),
    ]
