# Generated by Django 3.0.7 on 2020-06-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200613_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_street_address1',
            new_name='default_billing_street_address_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_street_address2',
            new_name='default_billing_street_address_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_street_address1',
            new_name='default_shipping_street_address_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_street_address2',
            new_name='default_shipping_street_address_2',
        ),
    ]
