# Generated by Django 3.0.7 on 2020-06-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockdrop_display'),
        ('users', '0003_auto_20200613_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_products',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_products',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.LikedProducts', to='products.Product'),
        ),
    ]
