# Generated by Django 3.0.7 on 2020-06-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockdrop_display'),
        ('users', '0004_auto_20200626_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedProducts',
            new_name='Liked',
        ),
    ]
