# Generated by Django 3.0.7 on 2020-06-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200626_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked',
            old_name='user',
            new_name='userprofile',
        ),
    ]
