# Generated by Django 3.0.7 on 2020-07-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200627_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_city',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_county',
            new_name='billing_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_name',
            new_name='billing_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_phone_number',
            new_name='billing_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_postcode',
            new_name='billing_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_street_address_1',
            new_name='billing_street_address_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_billing_street_address_2',
            new_name='billing_street_address_2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_county',
            new_name='shipping_county',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_name',
            new_name='shipping_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_phone_number',
            new_name='shipping_phone_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_postcode',
            new_name='shipping_postcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_street_address_1',
            new_name='shipping_street_address_1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_shipping_street_address_2',
            new_name='shipping_street_address_2',
        ),
    ]
