# Generated by Django 3.0.7 on 2020-07-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200701_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='billing_name',
            new_name='billing_full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='shipping_name',
            new_name='shipping_full_name',
        ),
    ]
