# Generated by Django 3.0.7 on 2020-07-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
