# Generated by Django 3.0.7 on 2020-07-07 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='sender',
            new_name='email',
        ),
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
