# Generated by Django 3.0.7 on 2020-07-01 04:35

import checkout.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20200701_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=checkout.models.CustomPhoneNumberField(max_length=128, region=None),
        ),
    ]
