# Generated by Django 3.0.7 on 2020-06-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200606_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blurb',
            field=models.CharField(default='', max_length=50),
        ),
    ]
