# Generated by Django 3.0.7 on 2020-06-07 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_blurb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='blurb',
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=4),
        ),
    ]
