# Generated by Django 3.0.7 on 2020-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200608_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='friendly_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
