# Generated by Django 3.0.7 on 2020-06-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200615_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdrop',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
