# Generated by Django 3.0.7 on 2020-07-04 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_stockdrop_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='admin_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), size=8),
        ),
    ]
