# Generated by Django 3.0.7 on 2020-07-04 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200704_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_tags',
        ),
    ]
