# Generated by Django 3.0.7 on 2020-07-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_quantity',
            field=models.BooleanField(default=False),
        ),
    ]
