# Generated by Django 3.0.7 on 2020-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_has_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='is_unique',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(default=1),
        ),
    ]
