# Generated by Django 3.0.7 on 2020-07-07 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200706_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=2),
        ),
    ]
