# Generated by Django 3.0.7 on 2020-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200707_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-popularity']},
        ),
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='times_purchased',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
